In [3]:
import numpy as np
#step 1: node, feature and edge representation in matrix form
A = np.matrix([
    [0, 1, 0, 0],
    [0, 0, 1, 1], 
    [0, 1, 0, 0],
    [1, 0, 1, 0]],
    dtype=float
)
X = np.matrix([
            [i, -i]
            for i in range(A.shape[0])
        ], dtype=float)
#2 feature columns per node. 
X


matrix([[ 0.,  0.],
        [ 1., -1.],
        [ 2., -2.],
        [ 3., -3.]])

In [4]:
#matrix multiplication rules, 
A * X

matrix([[ 1., -1.],
        [ 5., -5.],
        [ 1., -1.],
        [ 2., -2.]])

In [8]:
#add self loops which add the node features to the neighbors 
#add identity matrix to A to add self loops
I = np.matrix(np.eye(A.shape[0]))
I
A_hat = A + I
A_hat*X


matrix([[ 1., -1.],
        [ 6., -6.],
        [ 3., -3.],
        [ 5., -5.]])

In [11]:
W = np.matrix([
             [1, -1],
             [-1, 1]
])
relu(D_hat**-1 * A_hat * X * W)

NameError: name 'relu' is not defined

In [9]:
from networkx import karate_club_graph, to_numpy_matrix